"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const NormalAccount_1 = require("./NormalAccount");
const SavingsAccount_1 = require("./SavingsAccount");
const InvestmentAccount_1 = require("./InvestmentAccount");
var yesterdaydate = new Date();
var tomorrowdate = new Date();
yesterdaydate.setDate(yesterdaydate.getDate() - 1);
tomorrowdate.setDate(tomorrowdate.getDate() + 1);
const currentDate = new Date();
const oneYearFromNow = new Date(currentDate.getFullYear(), currentDate.getMonth() - 1, currentDate.getDate());
let normalAccount = new NormalAccount_1.NormalAccount();
console.log(normalAccount.deposit(100));
console.log(normalAccount.deposit(200));
console.log(normalAccount.withdraw(400));
console.log("Account debit = " + normalAccount.debit);
console.log(normalAccount.createStatement(yesterdaydate, tomorrowdate));
let savingsAccount = new SavingsAccount_1.SavingsAccount();
console.log("Saving account debit = " + savingsAccount.debit);
console.log(savingsAccount.deposit(100));
console.log(savingsAccount.withdraw(200));
console.log(savingsAccount.deposit(300));
console.log(savingsAccount.createStatement(yesterdaydate, tomorrowdate));
let investmentAccount = new InvestmentAccount_1.InvestmentAccount();
console.log(investmentAccount.deposit(100));
investmentAccount.interestStartDate = oneYearFromNow;
console.log("account balance + interest = " + investmentAccount.getBalanceWithInterest());
